# Generated by Django 5.1.15 on 2026-03-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_add_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_saved',
            field=models.BooleanField(default=False, help_text='True if the user explicitly saved this to their library.'),
        ),
    ]
